name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK with Buildozer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer & dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk build-essential \
          libncurses5 libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
          git libgl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
          libavformat-dev libavcodec-dev libfreetype6-dev

        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: cryptohunter-apk
    path: bin/*.apk
